Handling of invalid escape sequence '\]'
arutar/wininfparser pull request #5
Opened 2024-12-12 01:22 UTC by wnark

To fix this warning:
```
.venv/lib/python3.11/site-packages/wininfparser.py:865
  /opt/cloud-desktop/.venv/lib/python3.11/site-packages/wininfparser.py:865: DeprecationWarning: invalid escape sequence '\]'
```

2024-12-12 01:27 UTC, wnark commented
You may also want to use pyupgrade to check that the

2024-12-12 08:32 UTC, arutar requested changes
```
SepRE = re.compile('[^][";=]*(\\]|\\[|"|;|=)?')
```
To get rid of the warning try this code. I suggest replacing it with what I wrote. Please check the code I wrote, this warning does not appear for me. Correct the code in the merge request and I will add a fix

2024-12-13 07:43 UTC, wnark commented
this warning will only appear once in a brand new python container.

code:`SepRE = re.compile('[^][";=]*(\]|\[|"|;|=)?')` There will be a warning.
code:`SepRE = re.compile('[^][";=]*(\\]|\\[|"|;|=)?')` no warning

2024-12-13 07:48 UTC, wnark commented
I've updated it.thanks
@arutar

2024-12-13 08:16 UTC, merged